version: "3"
services:
  jenkins:
    build: ./jenkins/
    # image: jenkins/jenkins:lts
    user: jenkins
    ports:
      - "8081:8080"
      - "8443:8443"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_data:/var/jenkins_home
      - ./jenkins/home:/home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/:/opt/app/flask/
  flask:
    build: ./app/
    ports:
        - "5000:5000"
    volumes:
        - ./app:/code
